# Generated by Django 4.1.1 on 2022-09-07 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Uso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(max_length=64)),
                ('nombre_tradicional', models.CharField(max_length=32)),
                ('especie', models.CharField(max_length=16)),
                ('origen', models.CharField(max_length=32)),
                ('temporada', models.CharField(max_length=24)),
                ('estatus', models.BooleanField(default=True)),
                ('descripcion', models.TextField()),
                ('fertilizante', models.TextField()),
                ('riego', models.TextField()),
                ('iluminacion', models.TextField()),
                ('usos', models.ManyToManyField(to='app.uso')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.BinaryField(editable=True)),
                ('tipo', models.CharField(help_text='The MIMEType of the file', max_length=256)),
                ('planta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.planta')),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Analiticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planta')),
            ],
        ),
    ]
