# Generated by Django 4.1.1 on 2022-09-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='descripcion',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='planta',
            name='especie',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='planta',
            name='fertilizante',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='planta',
            name='iluminacion',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='planta',
            name='riego',
            field=models.TextField(max_length=256),
        ),
    ]
