# Generated by Django 4.1.1 on 2022-09-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_planta_descripcion_alter_planta_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planta',
            name='especie',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planta',
            name='fertilizante',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planta',
            name='iluminacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre_cientifico',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre_tradicional',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planta',
            name='origen',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planta',
            name='riego',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planta',
            name='temporada',
            field=models.TextField(),
        ),
    ]
