# Generated by Django 4.1.1 on 2022-09-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_planta_descripcion_alter_planta_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='dato',
            field=models.TextField(),
        ),
    ]
